/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Sycope Documentation",
  "tagline": "Software written By Engineers, For Engineers",
  "url": "https://documentation.sycope.com",
  "baseUrl": "/",
  "organizationName": "flowcontrol12",
  "projectName": "docu",
  "scripts": [
    "/js/prime-theme.js"
  ],
  "favicon": "img/favicon.ico",
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": true,
          "path": "./docs",
          "sidebarPath": "/data/sycope_documentation/docu_31/docu/sidebars.js",
          "routeBasePath": "/",
          "editCurrentVersion": true,
          "lastVersion": "current",
          "versions": {
            "current": {
              "label": "3.1.0"
            }
          }
        },
        "theme": {
          "customCss": [
            "/data/sycope_documentation/docu_31/docu/src/css/icons.css",
            "/data/sycope_documentation/docu_31/docu/src/css/custom.css",
            "/data/sycope_documentation/docu_31/docu/node_modules/@progress/kendo-theme-default/scss/icons/_index.scss"
          ]
        }
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-sass"
  ],
  "themes": [
    "docusaurus-theme-search-typesense"
  ],
  "themeConfig": {
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "typesense": {
      "typesenseCollectionName": "sycope",
      "typesenseServerConfig": {
        "nodes": [
          {
            "host": "d3tcn89uq3a6bs.cloudfront.net",
            "port": 443,
            "protocol": "https"
          }
        ],
        "apiKey": "YAyDMfr79zWoY3sUubNuLMyat9CY2lcp"
      },
      "contextualSearch": true,
      "typesenseSearchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "navbar": {
      "title": "sycope documentation",
      "logo": {
        "src": "img/logo-sycope.svg"
      },
      "items": [
        {
          "type": "html",
          "position": "right",
          "value": "<p style=\"margin: 0 -12px; color: white\">version:</p>"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [],
      "copyright": "Copyright © 2025 Sycope",
      "style": "light"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    }
  },
  "i18n": {
    "defaultLocale": "en-GB",
    "locales": [
      "en-GB"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "stylesheets": [
    {
      "href": "/css/theme-dark.css",
      "id": "prime-theme"
    }
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
